# +-----------------------------------------------------
# |         SERVER CONFIG
# +-----------------------------------------------------
server:
  port: 8080
  servlet:
    session:
      cookie:
        name: UISESSION

# +-----------------------------------------------------
# |         SPRING CONFIG
# +-----------------------------------------------------
spring:
  application:
    name: clients-services
  profiles:
    active: '@activatedProperties@'

# +-----------------------------------------------------
# |         SPRING DATASOURCE CONFIG
# +-----------------------------------------------------
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_CLIENTS_HOST:localhost}:${DB_CLIENTS_PORT:33060}/${DB_CLIENTS_NAME:clientsdb}
    username: ${DB_CLIENTS_USERNAME:clients}
    password: ${DB_CLIENTS_PASSWORD:clients2023++}
    hikari:
      poolName: clients-pool
      connection-timeout: 50000
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 10
      minimum-idle: 10
      connection-test-query: select 1 from dual
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    generate-ddl: true
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:/db/migration
    schemas: clientsdb
    repeatable-sql-migration-prefix: R
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql

# +-----------------------------------------------------
# |         MONITORING CONFIG
# +-----------------------------------------------------
management:
  server:
    port: 9090
  endpoint:
    info:
      enabled: true
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always
      status:
        http-mapping:
          down: 500
          fatal: 503
          out-of-service: 503
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      base-path: /monitor/actuator
      exposure:
        include: '*'
